/*

 @name    : 锅巴汉化 - Web汉化插件
 @author  : 麦子、JAR、小蓝、好阳光的小锅巴
 @version : V0.6.1 - 2019-07-09
 @website : http://www.g8hh.com
 @idle games : http://www.gityx.com
 @QQ Group : 627141737

*/

//1.汉化杂项
var cnItems = {
    _OTHER_: [],

    //未分类：
    'Save': '保存',
    'Export': '导出',
    'Import': '导入',
    'Settings': '设置',
    'Achievements': '成就',
    'Statistics': '统计',
    'Changelog': '更新日志',
    'Hotkeys': '快捷键',
    'ALL': '全部',
    'Default': '默认',
    'AUTO': '自动',
    'default': '默认',
    "points": "点数",
    "Reset for +": "重置得到 + ",
    "Currently": "当前",
    "Effect": "效果",
    "Cost": "成本",
    "Goal:": "目标:",
    "Reward": "奖励",
    "Start": "开始",
    "Exit Early": "提前退出",
    "Finish": "完成",
    "Milestone Gotten!": "获得里程碑！",
    "Milestones": "里程碑",
    "Completed": "已完成",
    "Default Save": "默认存档",
    "Delete": "删除",
    "No": "否",
    "Saves": "存档",
    "Options": "选项",
    "Yes": "是",
    "Are you sure?": "你确定吗？",
    "Edit Name": "编辑名称",
    "Info": "信息",
    "Currently:": "当前:",
    "Appearance": "外观",
    "How the game looks.": "游戏看起来如何。",
    "Theme": "主题",
    "Show milestones": "显示里程碑",
    "Show TPS meter at the bottom-left corner of the page.": "在页面左下角显示 TPS。",
    "Show TPS": "显示 TPS",
    "None": "无",
    "Align modifier units": "对齐概览单位",
    "Align numbers to the beginning of the unit in modifier view.": "在概览视图中将数字与单元的开头对齐。",
    "Select which milestones to display based on criterias.": "根据标准选择要显示的里程碑。",
    "All": "全部",
    "Classic": "经典",
    "Configurable": "可配置",
    "Duplicate": "复制",
    "Mute": "静音",
    "Unmute": "播放",
    "Join the Discord!": "加入 Discord!",
    "Fix export button and save": "修复导出按钮和保存",
    "ENABLED": "启用",
    "Export to file": "导出为文件",
    "Import clipboard": "从剪贴板导入",
    "Import file": "从文件导入",
    "DISABLED": "禁用",
    "Experience": "经验值",
    "Cancel": "取消",
    "gold": "金币",
    "Gold": "金币",
    "Goblins:": "哥布林:",
    "Gold:": "金币:",
    "Goblins /": "哥布林 /",
    "Goblins": "哥布林",
    "Dwarf Kingdom": "矮人王国",
    "Goblin Kingdom": "哥布林王国",
    "Wyrmling": "妖蛆",
    "gems cut": "宝石切割",
    "Exit Challenge": "退出挑战",
    "(Regen": "(回复",
    "[OFF]": "[关]",
    "(Unlocks Goblin Kingdom)": "(解锁哥布林王国)",
    "(Unlocks Dwarf Kingdom)": "(解锁矮人王国)",
    "Challenge (-": "挑战 (-",
    "Challenges": "挑战",
    "Max": "最大",
    "Goblin": "哥布林",
    "Blacksmith": "铁匠",
    "Lapidary": "宝石匠",
    "Mechanic": "机械工",
    "Miner": "矿工",
    "Peasant": "农夫",
    "Scholar": "学者",
    "Bronze:": "青铜:",
    "Auto Buy Max": "自动购买最大",
    "Auto Increase Max": "自动提升最大",
    "Auto Infuse": "自动灌注",
    "Bear": "熊",
    "Uru Runes:": "Uru符文:",
    "Uru": "Uru",
    "Upgrades": "升级",
    "Uru rune": "Uru符文",
    "Uru Rune": "Uru符文",
    "You Win!": "你赢了!",
    "Your scholars can conjured a single portal to let 50 men through. Perhaps you can find way to reinforce your army while in Hell.": "你的学者可以变出一个传送门让50个人通过。也许你能在地狱里想办法增援你的军队。",
    "Units": "单位",
    "unending wave of monsters and earn emblems to increase gold generation": "无尽的怪物浪潮和赚取徽章来增加金币生成",
    "Titanium:": "钛:",
    "Total Gold/sec:": "总金币/秒:",
    "Total Time:": "总时间:",
    "Troops": "军队",
    "Troops:": "军队:",
    "troops": "军队",
    "(adding": "(添加",
    "(Increases Dwarves efficiency by": "(使矮人的效率提高",
    "(multiplying output of": "(乘以输出",
    "% Conquered": "% 已征服",
    "% of Hell Conquered": "% 地狱已征服",
    "% stats)": "% 属性)",
    "adamant": "艾德曼",
    "Adamant:": "艾德曼:",
    "adamant/tick": "艾德曼/tick",
    "Adds ability to critically strike.": "增加暴击的能力。",
    "After defeating the dragon these lands are liberated and under your just rule. As peace time approaches your loyal scholars inform you of their latest findings.": "在打败巨龙之后，这些土地就被解放了，在你的公正统治下。随着和平时期的临近，忠实的学者们会告诉你他们的最新发现。",
    "Armory": "军械库",
    "Allows ability to dodge attacks.": "允许躲避攻击的能力。",
    "bronze": "青铜",
    "Chain Sword Module": "链剑模块",
    "Chance to attack twice.": "攻击两次的几率。",
    "choice": "选择",
    "Combat": "战斗",
    "Cost:": "成本:",
    "COST:": "成本:",
    "Construct": "构造",
    "DEF": "防御",
    "Cut Gems:": "切割宝石:",
    "Current Emblems:": "当前徽章:",
    "Slime": "史莱姆",
    "STR": "力量",
    "titanium": "钛",
    "Total Runic Power/sec:": "总符文力量/秒：",
    "Strength:": "力量:",
    "The Great Forge": "大熔炉",
    "Start Challenge": "开始挑战",
    "Scorpion": "蝎子",
    "Scholars:": "学者:",
    "Scholars": "学者",
    "Schematics": "图表",
    "Save Game": "保存游戏",
    "Satan and his forces have been driven back by the might, courage, and bravery of your people.": "撒但和他的势力被你百姓的力量、勇气和勇敢击退了。",
    "runic power": "符文之力",
    "Runes": "符文",
    "Relics:": "圣遗物:",
    "Primal Uru": "原始Uru",
    "Primal Runes": "原始符文",
    "Primal Nyd": "原始Nyd",
    "Primal Maan": "原始Maan",
    "Portals": "传送门",
    "Portals:": "传送门:",
    "\"A demonic plane of existance has been discovered and we fear an invasion is soon approaching! You must travel there and destroy the three heads of Lucifer to stop any future invasion!\"": "“我们已经发现了一个恶魔的存在，我们担心入侵即将到来！”你必须去那里摧毁路西法的三个头来阻止未来的入侵！\”",
    "Assign Goblins to help units in other kingdoms": "派遣哥布林帮助其他王国的单位",
    "Blacksmiths:": "铁匠:",
    "Brewmaster": "酿酒师",
    "Blacksmiths": "铁匠",
    "Brewmasters:": "酿酒大师：",
    "Defence:": "防御:",
    "Dragon": "龙",
    "Dwarf King": "矮人王",
    "Create Portal": "创建传送门",
    "Create Rune": "创造符文",
    "Demon Artifacts": "恶魔神器",
    "Demon Souls": "恶魔灵魂",
    "Demon Souls:": "恶魔灵魂:",
    "Demon Artifacts:": "恶魔神器:",
    "Dwarven Brewmasters": "矮人酿酒大师",
    "Dwarven Brewmasters:": "矮人酿酒大师:",
    "Dwarven Lapidaries:": "矮人宝石匠:",
    "Dwarven Miners:": "矮人矿工:",
    "Dwarven Miners": "矮人矿工",
    "Dwarven Lapidaries": "矮人宝石匠",
    "Ore /": "矿石 /",
    "ore": "矿石",
    "Ore:": "矿石:",
    "ore/tick": "矿石/tick",
    "iron/tick": "铁/tick",
    "mythril/tick": "秘银/tick",
    "OUTPUT:": "输出:",
    "Peasants": "农夫",
    "Peasants:": "农夫:",
    "Tier": "层级",
    "Runic Power:": "符文之力：",
    "Portal Closing in:": "传送门关闭还有:",
    "Max HP": "最大生命值",
    "Miners:": "矿工:",
    "mythril": "秘银",
    "Monsters Slain:": "击杀怪物:",
    "Monster": "怪物",
    "Mythril:": "秘银:",
    "iron": "铁",
    "Iron:": "铁:",
    "Infusion": "灌注",
    "knowledge": "知识",
    "Knowledge": "知识",
    "Knowledge:": "知识:",
    "HP": "生命值",
    "HP:": "生命值:",
    "Heroism:": "英雄主义:",
    "Goblin Mechanics:": "哥布林力学：",
    "Emblems:": "徽章:",
    "EFFECT:": "效果:",
    "Enter Hell": "进入地狱",
    "For King & Country!": "为了 国王与国家!",
    "Combat Level:": "战斗等级:",
    "Blood Transfusion Pauldrons": "输血肩甲",
    "Conjure Demon Soul": "召唤恶魔之魂",
    "Create Bronze Relic": "制作青铜器圣遗物",
    "Dwarven Skeleton": "矮人骷髅",
    "Each cut gem multiplies Gold Generation": "每切割一块宝石都会增加黄金产量",
    "Each Relic increases Runic Power gain": "每件圣遗物增加符文能量增益",
    "Each Rune adds +20 to Max HP & multiply Goblin assistance": "每个符文增加20点最大生命值并增加哥布林援助",
    "Each Rune adds +5 to": "每个符文+5",
    "Each Rune multiplies Peasant production": "每个符文增加农夫的产量",
    "Each Rune multiplies Peasant production & Goblin assistance": "每个符文增加农夫产量和哥布林援助",
    "Each Rune multiplies Runic Power gain": "每个符文增加符文能量增益",
    "Each Rune multiplies Runic Power gain & Goblin assistance": "每个符文增加符文能量增益和哥布林援助",
    "Engine Powered Boots": "引擎动力战靴",
    "Forge": "锻造",
    "From the depths of hell your rallying cry can be heard.": "从地狱深处可以听到你的战斗呐喊。",
    "Game Saved": "游戏已保存",
    "Game will autosave every 5 minutes": "游戏将自动保存每5分钟",
    "Goblin Chieftain": "哥布林首领",
    "Griffon": "狮鹫",
    "Hard Reset Game": "硬重置游戏",
    "Headquarters": "总部",
    "Human Kingdom": "人类王国",
    "Hydraulic Gauntlets": "液压护手",
    "Increase Adamant output": "提高艾德曼产量",
    "Increase Blacksmith Efficiency": "提高铁匠效率",
    "Increase Efficiency Max": "提升效率上限",
    "Increase Iron output": "增加铁产量",
    "Increase Mythril output": "提高秘银产量",
    "Increase Peasant Efficiency": "提高农夫效率",
    "Increase Regen.": "增加回复。",
    "Increase Titanium output": "增加钛产量",
    "Increases portal strength": "提升传送门力量",
    "Infuse Runic Power": "注入符文之力",
    "Lapidaries:": "宝石:",
    "Maan": "Maan",
    "Maan rune": "Maan符文",
    "Maan Runes:": "Maan符文：",
    "Mechanics": "力学",
    "Mechanics:": "力学:",
    "Metalurgy": "冶金学",
    "Nyd": "Nyd",
    "Nyd rune": "Nyd符文",
    "Nyd Rune": "Nyd符文",
    "Nyd Runes:": "Nyd符文:",
    "P.Maan Runes:": "P.Maan符文：",
    "P.Nyd Runes:": "P.Nyd符文:",
    "P.Uru Runes:": "P.Uru符文：",
    "Game Loaded": "游戏已加载",
    "Armory & Combat": "军械库 & 战斗",
    "Giant Lizard": "巨型蜥蜴",
    "[ON]": "[开]",
    "Forged!": "已锻造!",
    "Werewolf": "狼人",
    "Wyvern": "飞龙",
    "Lapidaries": "宝石匠",
    "Miners": "矿工",
    "Peasents": "农夫",
    "Fortress": "要塞",
    "You destory one of Lucifer's Faces": "你摧毁了路西法的一张脸",
    "": "",
    "": "",
    "": "",
    "": "",
    "": "",
    "": "",
    "": "",
    "": "",
    "": "",
    "": "",
    "": "",
    "": "",
    "": "",
    "": "",
    "": "",
    "": "",
    "": "",
    "": "",
    "": "",
    "": "",
    "": "",
    "": "",
    "": "",
    "": "",
    "": "",
    "": "",
    "": "",
    "": "",
    "": "",
    "": "",
    "": "",
    "": "",
    "": "",
    "": "",
    "": "",
    "": "",
    "": "",
    "": "",
    "": "",
    "": "",
    "": "",
    "": "",
    "": "",
    "": "",
    "": "",
    "": "",
    "": "",
    "": "",
    "": "",
    "": "",
    "": "",
    "": "",
    "": "",
    "": "",
    "": "",
    "": "",
    "": "",
    "": "",
    "": "",
    "": "",
    "by": "by",
    "Pauldrons": "护肩",
    "Materials": "材料",
    "Sword": "剑",
    "Smelter": "熔炉",
    "Shield": "盾牌",
    "Plate": "板甲",
    "Greaves": "护胫",
    "Gauntlets": "护手",
    "Helm": "头盔",
    "Legs": "护腿",
    // 图标代码，不能汉化
    "Jacorb's Games": "Jacorb's Games",
    "???": "???",
    "←": "←",
    "→": "→",
    "↑": "↑",
    "<-": "<-",
    "↓": "↓",
    "%)": "%)",
    "/": "/",
    "->": "->",
    "": "",
    "": "",
    "": "",
    "": "",
    "": "",
    "": "",
    "": "",
    "": "",
    "": "",
    "": "",
    "": "",
    "": "",
    "": "",
    "+": "+",
    ".": ".",
    "…": "…",
    ":": ":",
    "-": "-",
    "|": "|",
    "(": "(",
    ")": ")",
    "Scientific": "科学计数法",
    "Standard": "标准",
    "Blind": "盲文",
    "Letters": "字母",
    "Mixed Engineering": "混合工程",
    "Mixed Scientific": "混合科学",
    "Chemistry": "化学",
    "Engineering": "工程符号",
    "By Jacorb90": "By Jacorb90",
    "content_copy": "content_copy",
    "library_books": "library_books",
    "discord": "discord",
    "drag_handle": "drag_handle",
    "edit": "edit",
    "forum": "forum",
    "content_paste": "content_paste",
    "delete": "delete",
    "info": "info",
    "settings": "settings",
    'Twitter': 'Twitter',
    "Discord": "Discord",
    "Facebook": "Facebook",
    "Instagram": "Instagram",
    "gityxcom": "gityxcom",
    "Footer": "Footer",
    "Wiki": "Wiki",
    "gityx": "gityx",

    //树游戏
    'Loading...': '加载中...',
    'ALWAYS': '一直',
    'HARD RESET': '硬重置',
    'Export to clipboard': '导出到剪切板',
    'INCOMPLETE': '不完整',
    'HIDDEN': '隐藏',
    'AUTOMATION': '自动',
    'NEVER': '从不',
    'ON': '打开',
    'OFF': '关闭',
    'SHOWN': '显示',
    'Play Again': '再次游戏',
    'Keep Going': '继续',
    'The Modding Tree Discord': '模型树Discord',
    'You have': '你有',
    'It took you {{formatTime(player.timePlayed)}} to beat the game.': '花费了 {{formatTime(player.timePlayed)}} 时间去通关游戏.',
    'Congratulations! You have reached the end and beaten this game, but for now...': '恭喜你！ 您已经结束并通关了本游戏，但就目前而言...',
    'Main Prestige Tree server': '主声望树服务器',
    'Reach {{formatWhole(ENDGAME)}} to beat the game!': '达到 {{formatWhole(ENDGAME)}} 去通关游戏!',
    "Loading... (If this takes too long it means there was a serious error!": "正在加载...（如果这花费的时间太长，则表示存在严重错误！",
    'Loading... (If this takes too long it means there was a serious error!)←': '正在加载...（如果时间太长，则表示存在严重错误！）←',
    'Main\n\t\t\t\tPrestige Tree server': '主\n\t\t\t\t声望树服务器',
    'The Modding Tree\n\t\t\t\t\t\t\tDiscord': '模型树\n\t\t\t\t\t\t\tDiscord',
    'Please check the Discord to see if there are new content updates!': '请检查 Discord 以查看是否有新的内容更新！',
    'aqua': '水色',
    'AUTOMATION, INCOMPLETE': '自动化，不完整',
    'LAST, AUTO, INCOMPLETE': '最后，自动，不完整',
    'NONE': '无',
    'P: Reset for': 'P: 重置获得',
    'Gityx游戏': 'Gityx游戏',
    'Git游戏': 'Git游戏',
    'QQ群号': 'QQ群号',
    'x': 'x',
    'QQ群号:': 'QQ群号:',
    '* 启用后台游戏': '* 启用后台游戏',
    '更多同类游戏:': '更多同类游戏:',
    'i': 'i',
    'I': 'I',
    'II': 'II',
    'III': 'III',
    'IV': 'IV',
    'V': 'V',
    'VI': 'VI',
    'VII': 'VII',
    'VIII': 'VIII',
    'X': 'X',
    'XI': 'XI',
    'XII': 'XII',
    'XIII': 'XIII',
    'XIV': 'XIV',
    'XV': 'XV',
    'XVI': 'XVI',
    'A': 'A',
    'B': 'B',
    'C': 'C',
    'D': 'D',
    'E': 'E',
    'F': 'F',
    'G': 'G',
    'H': 'H',
    'I': 'I',
    'J': 'J',
    'K': 'K',
    'L': 'L',
    'M': 'M',
    'N': 'N',
    'O': 'O',
    'P': 'P',
    'Q': 'Q',
    'R': 'R',
    'S': 'S',
    'T': 'T',
    'U': 'U',
    'V': 'V',
    'W': 'W',
    'X': 'X',
    'Y': 'Y',
    'Z': 'Z',
    'a': 'a',
    'b': 'b',
    'c': 'c',
    'd': 'd',
    'e': 'e',
    'f': 'f',
    'g': 'g',
    'h': 'h',
    'i': 'i',
    'j': 'j',
    'k': 'k',
    'l': 'l',
    'm': 'm',
    'n': 'n',
    'o': 'o',
    'p': 'p',
    'q': 'q',
    'r': 'r',
    's': 's',
    't': 't',
    'u': 'u',
    'v': 'v',
    'w': 'w',
    'x': 'x',
    'y': 'y',
    'z': 'z',
    '<': '<',
    '<<': '<<',
    '>': '>',
    '>>': '>>',
    'Jan': '1月',
    'Feb': '2月',
    'Mar': '3月',
    'Apr': '4月',
    'May': '5月',
    'Jun': '6月',
    'Jul': '7月',
    'Aug': '8月',
    'Sep': '9月',
    'Oct': '10月',
    'Nov': '11月',
    'Dec': '12月',
    '': '',
    '': '',
    '': '',
    '': '',
    '': '',

}


//需处理的前缀，此处可以截取语句开头部分的内容进行汉化
//例如：Coin: 13、Coin: 14、Coin: 15... 这种有相同开头的语句
//可以在这里汉化开头："Coin: ":"金币: "
var cnPrefix = {
    "\n": "\n",
    "                   ": "                   ",
    "                  ": "                  ",
    "                 ": "                 ",
    "                ": "                ",
    "               ": "               ",
    "              ": "              ",
    "             ": "             ",
    "            ": "            ",
    "           ": "           ",
    "          ": "          ",
    "         ": "         ",
    "        ": "        ",
    "       ": "       ",
    "      ": "      ",
    "     ": "     ",
    "    ": "    ",
    "   ": "   ",
    "  ": "  ",
    " ": " ",
    //树游戏
    "\t\t\t": "\t\t\t",
    "\n\n\t\t": "\n\n\t\t",
    "\n\t\t": "\n\t\t",
    "\t": "\t",
    "Show Milestones: ": "显示里程碑：",
    "Autosave: ": "自动保存: ",
    "Offline Prod: ": "离线生产: ",
    "Completed Challenges: ": "完成的挑战: ",
    "High-Quality Tree: ": "高质量树贴图: ",
    "Offline Time: ": "离线时间: ",
    "Theme: ": "主题: ",
    "Anti-Epilepsy Mode: ": "抗癫痫模式：",
    "In-line Exponent: ": "直列指数：",
    "Single-Tab Mode: ": "单标签模式：",
    "Time Played: ": "已玩时长：",
    "Shift-Click to Toggle Tooltips: ": "Shift-单击以切换工具提示：",
    "Notation: ": "符号: ",
    "Toggle Music: ": "切换声音: ",
    "Animations: ": "动画: ",
    "Current Endgame: ": "当前终局: ",
    "Space Background: ": "太空背景: ",
    "Fight ": "对抗 ",
    "Adamant ": "艾德曼",
    "Buy ": "购买",
    "Bronze ": "青铜",
    "Iron ": "铁",
    "Titanium ": "钛",
    "Mythril ": "秘银",
    "Unlock ": "解锁",
    "Upgrade ": "升级 ",
    "": "",
    "": "",
    "": "",
    "": "",
    "": "",
    "": "",
    "": "",
    "": "",
}

//需处理的后缀，此处可以截取语句结尾部分的内容进行汉化
//例如：13 Coin、14 Coin、15 Coin... 这种有相同结尾的语句
//可以在这里汉化结尾：" Coin":" 金币"
var cnPostfix = {
    "                   ": "                   ",
    "                  ": "                  ",
    "                 ": "                 ",
    "                ": "                ",
    "               ": "               ",
    "              ": "              ",
    "             ": "             ",
    "            ": "            ",
    "           ": "           ",
    "          ": "          ",
    "         ": "         ",
    "        ": "        ",
    "       ": "       ",
    "      ": "      ",
    "     ": "     ",
    "    ": "    ",
    "   ": "   ",
    "  ": "  ",
    " ": " ",
    "\n": "\n",
    "\n\t\t\t": "\n\t\t\t",
    "\t\t\n\t\t": "\t\t\n\t\t",
    "\t\t\t\t": "\t\t\t\t",
    "\n\t\t": "\n\t\t",
    "\t": "\t",
    "/sec)": "/秒)",
    ' I': ' I',
    ' II': ' II',
    ' III': ' III',
    ' IV': ' IV',
    ' V': ' V',
    ' VI': ' VI',
    ' VII': ' VII',
    ' VIII': ' VIII',
    ' X': ' X',
    ' XI': ' XI',
    ' XII': ' XII',
    ' XIII': ' XIII',
    ' XIV': ' XIV',
    ' XV': ' XV',
    ' XVI': ' XVI',
    " Faces Destroyed": "脸数被摧毁",
    " Unlocked": " 已解锁",
    "": "",
    "": "",
    "": "",
}

//需排除的，正则匹配
var cnExcludeWhole = [
    /^(\d+)$/,
    /^\s*$/, //纯空格
    /^([\d\.]+):([\d\.]+)$/,
    /^([\d\.]+):([\d\.]+):([\d\.]+)$/,
    /^([\d\.]+):([\d\.]+):([\d\.]+):([\d\.]+)$/,
    /^([\d\.]+):([\d\.]+):([\d\.]+):([\d\.]+):([\d\.]+)$/,
    /^([\d\.]+)s$/,
    /^([\d\.]+)h$/,
    /^([\d\.]+)m$/,
    /^([\d\.]+)m ([\d\.]+)s$/,
    /^([\d\.]+)h ([\d\.]+)m ([\d\.]+)s$/,
    /^([\d\.]+)d ([\d\.]+)h ([\d\.]+)m ([\d\.]+)s$/,
    /^([\d\.]+)y ([\d\.]+)d ([\d\.]+)h ([\d\.]+)m ([\d\.]+)s$/,
    /^([\d\.]+)y ([\d\.]+)d ([\d\.]+)h$/,
    /^([\d\.]+)\-([\d\.]+)\-([\d\.]+)$/,
    /^([\d\.]+)e([\d\.,]+)$/,
    /^([\d\.]+)$/,
    /^×([\d\.]+)$/,
    /^x([\d\.]+)$/,
    /^v([\d\.]+)$/,
    /^\$([\d\.]+)$/,
    /^\(([\d\.]+)\)$/,
    /^\(([\d\.]+), ([\d\.]+)\)$/,
    /^([\d\.]+)\%$/,
    /^\+([\d\.]+)\%$/,
    /^\-([\d\.]+)\%$/,
    /^([\d\.]+)\/([\d\.]+)$/,
    /^([\d\.]+)\/([\d\.,]+)$/,
    /^([\d\.,]+)\/([\d\.,]+)$/,
    /^\(([\d\.]+)\/([\d\.]+)\)$/,
    /^\(([\d\.]+),([\d\.]+)\)$/,
    /^\(\-([\d\.]+),([\d\.]+)\)$/,
    /^\(\-([\d\.]+),\-([\d\.]+)\)$/,
    /^\(([\d\.]+),\-([\d\.]+)\)$/,
    /^成本(.+)$/,
    /^\(([\d\.]+)\%\)$/,
    /^([\d\.]+):([\d\.]+):([\d\.]+)$/,
    /^([\d\.]+)\-([\d\.]+)\-([\d\.]+) ([\d\.]+):([\d\.]+):([\d\.]+)$/,
    /^([\d\.]+)\/([\d\.]+)\/([\d\.]+)$/,
    /^([\d\.]+)\/([\d\.]+)\/([\d\.]+) ([\d\.]+):([\d\.]+):([\d\.]+)$/,
    /^\[([\d\.]+):([\d\.]+):([\d\.]+)\]$/,
    /^([\d\.]+)K$/,
    /^([\d\.]+)M$/,
    /^([\d\.]+)B$/,
    /^([\d\.]+) K$/,
    /^([\d\.]+) M$/,
    /^([\d\.]+) B$/,
    /^([\d\.]+) T$/,
    /^([\d\.]+) Qi$/,
    /^([\d\.]+) Qa$/,
    /^([\d\.]+) Sp$/,
    /^([\d\.]+) Oc$/,
    /^([\d\.]+) Dc$/,
    /^([\d\.]+) UDc$/,
    /^([\d\.]+) No$/,
    /^([\d\.]+) Sx$/,
    /^([\d\.]+) QaDc$/,
    /^([\d\.]+)s$/,
    /^([\d\.]+)x$/,
    /^x([\d\.]+)$/,
    /^([\d\.,]+)$/,
    /^\$([\d\.,]+)$/,
    /^\+([\d\.,]+)$/,
    /^\-([\d\.,]+)$/,
    /^([\d\.,]+)x$/,
    /^x([\d\.,]+)$/,
    /^×([\d\.,]+)$/,
    /^([\d\.,]+) \/ ([\d\.,]+)$/,
    /^([\d\.]+)e([\d\.,]+)$/,
    /^([\d\.]+)e([\d\.,]+) \/ ([\d\.]+)e([\d\.,]+)$/,
    /^\$([\d\.]+)e([\d\.,]+)$/,
    /^([\d\.,]+)\/([\d\.]+)e([\d\.,]+)$/,
    /^([\d\.]+)e([\d\.,]+)\/([\d\.]+)e([\d\.,]+)$/,
    /^([\d\.]+)e\+([\d\.,]+)$/,
    /^e([\d\.]+)e([\d\.,]+)$/,
    /^x([\d\.]+)e([\d\.,]+)$/,
    /^([\d\.]+)e([\d\.,]+)x$/,
    // /^([\uD800-\uDBFF][\uDC00-\uDFFF])|([\u2600-\u27BF])|([\u2300-\u23FF])|([\u2B50-\u2B55])|([\u203C-\u3299])|[\u21A9\u21AA\u25B6\u25C0\u2B06\u2B07\u2B05\u2B95\u2B99\u2B9A]+$/,
    // /^([\uD800-\uDBFF][\uDC00-\uDFFF])|([\u2600-\u27BF])|([\u2300-\u23FF])|([\u2B50-\u2B55])|([\u203C-\u3299])+$/,
    // /^[\uD800-\uFFFF]+$/,
    /^[\u4E00-\u9FA5]+$/
];
var cnExcludePostfix = [
]

//正则替换，带数字的固定格式句子
//纯数字：(\d+)
//字母加数字：([\d\.]+[A-Za-z])
//逗号：([\d\.,]+)
//小数点：([\d\.]+)
//原样输出的字段：(.+)
//换行加空格：\n(.+)
//&nbsp;空格：\xA0
var cnRegReplace = new Map([
    [/^([\d\.]+) hours ([\d\.]+) minutes ([\d\.]+) seconds$/, '$1 小时 $2 分钟 $3 秒'],
    [/^You are gaining (.+) elves per second$/, '你每秒获得 $1 精灵'],
    [/^You have (.+) points$/, '你有 $1 点数'],
    [/^Next at (.+) points$/, '下一个在 $1 点数'],
    [/^Jan ([\d\.,]+) ([\d\.,]+), ([\d\.,]+):([\d\.,]+)$/, '$2 年 1 月 $1, $3:$4'],
    [/^Feb ([\d\.,]+) ([\d\.,]+), ([\d\.,]+):([\d\.,]+)$/, '$2 年 2 月 $1, $3:$4'],
    [/^Mar ([\d\.,]+) ([\d\.,]+), ([\d\.,]+):([\d\.,]+)$/, '$2 年 3 月 $1, $3:$4'],
    [/^Apr ([\d\.,]+) ([\d\.,]+), ([\d\.,]+):([\d\.,]+)$/, '$2 年 4 月 $1, $3:$4'],
    [/^May ([\d\.,]+) ([\d\.,]+), ([\d\.,]+):([\d\.,]+)$/, '$2 年 5 月 $1, $3:$4'],
    [/^Jun ([\d\.,]+) ([\d\.,]+), ([\d\.,]+):([\d\.,]+)$/, '$2 年 6 月 $1, $3:$4'],
    [/^Jul ([\d\.,]+) ([\d\.,]+), ([\d\.,]+):([\d\.,]+)$/, '$2 年 7 月 $1, $3:$4'],
    [/^Aug ([\d\.,]+) ([\d\.,]+), ([\d\.,]+):([\d\.,]+)$/, '$2 年 8 月 $1, $3:$4'],
    [/^Sep ([\d\.,]+) ([\d\.,]+), ([\d\.,]+):([\d\.,]+)$/, '$2 年 9 月 $1, $3:$4'],
    [/^Oct ([\d\.,]+) ([\d\.,]+), ([\d\.,]+):([\d\.,]+)$/, '$2 年 10 月 $1, $3:$4'],
    [/^Nov ([\d\.,]+) ([\d\.,]+), ([\d\.,]+):([\d\.,]+)$/, '$2 年 11 月 $1, $3:$4'],
    [/^Dec ([\d\.,]+) ([\d\.,]+), ([\d\.,]+):([\d\.,]+)$/, '$2 年 12 月 $1, $3:$4'],
    [/^([\d\.]+)\/sec$/, '$1\/秒'],
    [/^([\d\.]+)\/s$/, '$1\/秒'],
    [/^\(\+([\d\.]+)\/s\)$/, '(+$1\/秒)'],
    [/^([\d\.,]+)\/sec$/, '$1\/秒'],
    [/^([\d\.,]+) OOMs\/sec$/, '$1 OOMs\/秒'],
    [/^([\d\.]+) OOMs\/sec$/, '$1 OOMs\/秒'],
    [/^([\d\.]+)e([\d\.,]+)\/sec$/, '$1e$2\/秒'],
    [/^requires ([\d\.]+) more research points$/, '需要$1个研究点'],
    [/^([\d\.]+)e([\d\.,]+) points$/, '$1e$2 点数'],
    [/^([\d\.]+) elves$/, '$1 精灵'],
    [/^\+([\d\.]+) elves$/, '+$1 精灵'],
    [/^\+([\d\.]+)\% elves$/, '+$1% 精灵'],
    [/^([\d\.]+)d ([\d\.]+)h ([\d\.]+)m$/, '$1天 $2小时 $3分'],
    [/^([\d\.]+)h ([\d\.]+)m$/, '$1小时 $2分'],
    [/^([\d\.]+)m ([\d\.]+)s$/, '$1分钟 $2秒'],
    [/^([\d\.]+)e([\d\.,]+) elves$/, '$1e$2 精灵'],
    [/^\+([\d\.,]+) elves$/, '+$1 精灵'],
    [/^\/([\d\.,]+)s\)$/, '/$1秒)'],
    [/^([\d\.,]+) elves$/, '$1 精灵'],
    [/^at ([\d\.,]+) Heroism$/, '在 $1 英雄主义'],
    [/^Tier ([\d\.,]+)$/, '层级 $1'],
    [/^Day ([\d\.,]+)$/, '天数 $1'],
    [/^Your troops diminish by ([\d\.,]+)$/, '你的军队减少了 $1'],
    [/^You find ([\d\.,]+) Demon Artifact$/, '你发现了 $1 恶魔神器'],
    [/^You find ([\d\.,]+) Demon Artifacts$/, '你发现了 $1 恶魔神器'],
    [/^Hard Reset Game \n Click ([\d\.,]+) More Times$/, '硬重置游戏 \n 请再点击 $1 次'],
    [/^level ([\d\.,]+) \/ ([\d\.,]+)$/, '等级 $1 \/ $2'],
    [/^level: ([\d\.,]+) \/ ([\d\.,]+)$/, '等级 $1 \/ $2'],
    [/^\*(.+) to electricity gain$/, '\*$1 到电力增益'],
    [/^Cost: (.+) points$/, '成本：$1 点数'],
    [/^Req: (.+) elves$/, '要求：$1 精灵'],
    [/^Req: (.+) \/ (.+) elves$/, '要求：$1 \/ $2 精灵'],
    [/^Usages: (\d+)\/$/, '用途：$1\/'],
    [/^workers: (\d+)\/$/, '工人：$1\/'],

]);